import os
import json
import pytest
import numpy as np
from scipy.interpolate import interp1d
from bolus_tracking import gamma_fun, auto_estimate_params, fit_bolus

def test_gamma_fun_math():
    """
    Test basic properties of the gamma_fun to ensure it returns expected shapes/values.
    """
    t = np.linspace(0, 10, 100)
    params = [1.0, 5.0, 2.0, 0.0] # Amp=1, T2p=5, FWHM=2, Base=0
    
    y = gamma_fun(t, *params)
    assert len(y) == 100
    assert not np.any(np.isnan(y))
    # Verify the function has a single peak within the time range
    peak_idx = np.argmax(y)
    assert 0 < peak_idx < len(y) - 1, "Peak should not be at the boundary"
    # The function should rise before the peak and fall after
    assert y[peak_idx] >= y[0], "Peak value should be >= first value"
    assert y[peak_idx] >= y[-1], "Peak value should be >= last value"

@pytest.mark.skipif(not os.path.exists("parity_test_data.json"), reason="Parity test data not generated yet")
def test_matlab_parity():
    """
    Loads parity_test_data.json generated by ExportTestData.m
    and asserts that the Python implementation matches MATLAB's numeric results.
    """
    with open("parity_test_data.json", "r") as f:
        data = json.load(f)
        
    fr = data["Fr"]
    up_f = 20
    
    for roi_key, roi_data in data.items():
        if roi_key == "Fr":
            continue
            
        y_raw = np.array(roi_data["yRaw"])
        tl_raw = np.array(roi_data["tlRaw"])
        
        # Upsample trace the same way MATLAB does: spline interpolation
        tl_us = np.linspace(0, len(y_raw) / fr, len(y_raw) * up_f)
        spline_interp = interp1d(tl_raw, y_raw, kind='cubic', fill_value='extrapolate')
        y_us = spline_interp(tl_us)
        
        # Test 1: Auto Estimation Parity
        if "InitAmp" in roi_data:
            matlab_init = [roi_data["InitAmp"], roi_data["InitT2p"], roi_data["InitFWHM"], roi_data["InitM"]]
            py_init, start_idx, end_idx = auto_estimate_params(y_us, tl_us, fr, up_f)
            
            # Assert initial parameters match
            np.testing.assert_allclose(py_init, matlab_init, rtol=1e-2, err_msg=f"Auto-estimation failed parity for {roi_key}")
            
        # Test 2: Curve Fitting Parity
        if "beta" in roi_data:
            matlab_beta = np.array(roi_data["beta"])
            
            # Use MATLAB's exact initial params to isolate fitting logic test
            popt, pcov = fit_bolus(tl_us[start_idx:end_idx], y_us[start_idx:end_idx], matlab_init)
            
            assert popt is not None, f"Python curve_fit failed to converge for {roi_key}"
            
            # We use a looser tolerance (1e-1) for parameters since Scipy 'trf' + 'cauchy' 
            # uses slightly different internal steps than MATLAB's nlinfit, 
            # but the final fit curve and AUC should match extremely well.
            np.testing.assert_allclose(popt, matlab_beta, rtol=1e-1, err_msg=f"Fitted parameters failed parity for {roi_key}")
            
            # Check the actual curve match (this is what matters for AUC)
            if "fitTr" in roi_data:
                matlab_fit_tr = np.array(roi_data["fitTr"])
                # Generate Python curve over the same evaluation points
                t_eval = np.linspace(0, len(y_us[start_idx:end_idx]) / (fr*up_f), len(y_us[start_idx:end_idx]))
                py_fit_tr = gamma_fun(t_eval, *popt)
                
                # Check that the curves visually/numerically match
                np.testing.assert_allclose(py_fit_tr, matlab_fit_tr, rtol=1e-2, err_msg=f"Fitted curve failed parity for {roi_key}")
